cmssw        = /afs/cern.ch/user/p/psilva/work/HGCal/Patatrack/CMSSW_15_0_0_pre2/src
eosdir       = /eos/cms/store/group/dpg_hgcal/comm_hgcal/Production/
avg_pileup   = 200
pileup_input = $(eosdir)/MinBias_TuneCP5_14TeV-pythia8_CMSSW_15_0_0_pre3
executable   = runLocalGeneration.sh
arguments    = -c $(cmssw) -m HGCalCommissioning/LocalProduction/python/$(mcmfrag)_cfi.py -n $(nevts) -s $(simonly) -o $(transfer_output_files) -a $(aged) --avg_pileup $(avg_pileup) --pileup_input $(pileup_input)
output       = $(ClusterId).out
error        = $(ClusterId).err
log          = $(ClusterId).log
output_destination = root://eosuser.cern.ch/$(eosdir)/$(dataset)/
MY.XRDCP_CREATE_DIR = True
transfer_output_files   = Events_$(ProcId).root
+JobFlavour  = "testmatch"
+AccountingGroup = "group_u_CMST3.all"
MY.WantOS    = "el9"

queue 100 dataset mcmfrag nevts simonly aged from (
      TTbar_TuneCP5_14TeV-pythia8_PU200_vanilla_CMSSW_15_0_0_pre2 TTbar_14TeV_TuneCP5_Pythia8 100 0 vanilla
      #TTbar_TuneCP5_14TeV-pythia8_PU200_startup_fixedareasn_CMSSW_14_1_0_pre1_Extended2026D99  TTbar_14TeV_TuneCP5_Pythia8 100 0 SimCalorimetry.HGCalSimProducers.hgcalDigitizer_cfi.HGCal_setRealisticStartupNoise_fixedSiPMTileAreasAndSN
      #TTbar_TuneCP5_14TeV-pythia8_PU200_startup_nofluence_CMSSW_14_1_0_pre1_Extended2026D99  TTbar_14TeV_TuneCP5_Pythia8 100 0 SimCalorimetry.HGCalSimProducers.hgcalDigitizer_cfi.HGCal_ignoreFluence
      #TTbar_TuneCP5_14TeV-pythia8_PU200_startup_nonoise_CMSSW_14_1_0_pre1_Extended2026D99  TTbar_14TeV_TuneCP5_Pythia8 100 0 SimCalorimetry.HGCalSimProducers.hgcalDigitizer_cfi.HGCal_ignoreNoise
      #TTbar_TuneCP5_14TeV-pythia8_PU200_startup_CMSSW_14_1_0_pre1_Extended2026D99 TTbar_14TeV_TuneCP5_Pythia8 100 0 SimCalorimetry/HGCalSimProducers/hgcalDigitizer_cfi.HGCal_setRealisticStartupNoise
      #TTbar_TuneCP5_14TeV-pythia8_PU200_aged_CMSSW_14_1_0_pre1_Extended2026D99 TTbar_14TeV_TuneCP5_Pythia8 100 0 SimCalorimetry/HGCalSimProducers/hgcalDigitizer_cfi.HGCal_setEndOfLifeNoise
) 

